version: "3.8"

services:

  php:
    container_name: ${HOST_NAME}_php
    image: ghcr.io/local-deploy/php8.1-fpm

    ports:
      - "9000:9000"
    environment:
      - "DOCUMENT_ROOT=${DOCUMENT_ROOT:-/var/www/}"
      - "HOST_NAME=${HOST_NAME:-localhost}"
      - "LOCALTIME=${LOCALTIME:-Europe/Moscow}"
      - "PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}"
      - "PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-100M}"
      - "PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-100M}"
      - "PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-50}"
      - "PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-60}"
      - "XDEBUG=develop"
      - "XDEBUG_IDE_KEY=${XDEBUG_IDE_KEY:-PHPSTORM}"
      - "XDEBUG_PORT=${XDEBUG_PORT:-9003}"

    volumes:
      - "./:/var/www/"

  nginx:
    container_name: ${HOST_NAME}_nginx
    image: nginx:alpine
    working_dir: "/var/www"
    ports:
      - "80:80"

    volumes:
      - "./:/var/www/"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php

    networks:
      default:
        aliases:
          - test-task_default
  db:
    container_name: ${HOST_NAME}_db
    image: alterway/mysql:${MYSQL_VERSION}
    command: --innodb_strict_mode=off --innodb_flush_log_at_trx_commit=2 --innodb_flush_method=O_DIRECT --transaction-isolation=READ-COMMITTED --sql_mode=
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      LOCALTIME: ${LOCALTIME:-Europe/Moscow}
    volumes:
      - "./.docker/volume/db/:/var/lib/mysql/:delegated"
    ports:
      - "3306:3306"
